### ISSUE TITLE
Recommended way to use as part of an Azure DevOps pipeline

### ISSUE THREAD

**Issue by moerketh** [Azure/arm-ttk#507]
What is the recommended way to use arm-ttk as part of an Azure DevOps (Microsoft hosted) pipeline?

I'm attempting to run arm-ttk on a single main.json file generated with bicep build.

I have tried the "Run ARM TTK Tests" marketplace extension by @sam-cogan . It fails, but I am not sure why.

I had configured the pipeline like this:
```
trigger:
- master

name: Deploy Bicep files

variables:
  templateFile: './IaC/main.bicep'

pool:
  vmImage: windows-latest

stages:
- stage: Build
  jobs:
  - job: compile
    workspace:
      clean: all 
    steps:
    - task: PowerShell@2
      displayName: Build bicep to ARM
      inputs:
        targetType: inline
        script: |
          az bicep install
          az bicep build --file $(templateFile)
    - task: RunARMTTKTests@1
      inputs:
        templatelocation: '$(Pipeline.Workspace)\s\IaC\main.json'
        resultLocation: '$(System.DefaultWorkingDirectory)\results'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: '$(System.DefaultWorkingDirectory)\results\*-armttk.xml'
```

The relevant output is:
```
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Failures found in test results
##[debug]At D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.2.15\invoke-ttk.psm1:124 char:13
##[debug]+             throw "Failures found in test results"
##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : OperationStopped: (Failures found in test results:String) [], RuntimeException
##[debug]    + FullyQualifiedErrorId : Failures found in test results
##[debug] 
##[debug]Script stack trace:
##[debug]at Invoke-TTK, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.2.15\invoke-ttk.psm1: line 124
##[debug]at <ScriptBlock>, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.2.15\powershell.ps1: line 39
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Management.Automation.RuntimeException: Failures found in test results
```

Automating the steps from the documentation [here ](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/test-toolkit#install-on-windows). I removed the extension tasks from the pipeline and added the following powershell tasks:

```
    - task: PowerShell@2
      displayName: Install ARM Test Toolkit
      inputs:
        pwsh: true
        failOnStderr: true
        targetType: inline
        script: |
          Invoke-WebRequest "https://aka.ms/arm-ttk-latest" -OutFile "$(Build.BinariesDirectory)/arm-ttk-latest.zip"
          Expand-Archive -LiteralPath "$(Build.BinariesDirectory)/arm-ttk-latest.zip" -DestinationPath "$(Build.BinariesDirectory)/arm-ttk" -Force
          Set-Location "$(Build.BinariesDirectory)/arm-ttk"
          Get-ChildItem *.ps1, *.psd1, *.ps1xml, *.psm1 -Recurse | Unblock-File
    - task: PowerShell@2
      displayName: Run ARM Test Toolkit
      inputs:
        targetType: inline
        failOnStderr: true
        pwsh: true
        script: |
          Set-Location "$(Build.BinariesDirectory)/arm-ttk/arm-ttk"
          Import-Module .\arm-ttk.psd1
          $testOutput = @(Test-AzTemplate -TemplatePath $(Pipeline.Workspace)\s\IaC\main.json)
          $testOutput

          if ($testOutput | Where-Object { $_.Errors }) {
              exit 1 
          }
          else {
              exit 0
          } 
```

This fails with what is probably also the root cause of the extension failing. ​The output is:
```
E##[error]D:\a\1\b\arm-ttk\arm-ttk\testcases\deploymentTemplate\apiVersions-Should-Be-Recent.test.ps1 : Api versions must be the latest or under 2 years old (730 days) - API version 2019-09-01 of Microsoft.KeyVault/vaults/secrets is 732 days old
At D:\a\1\b\arm-ttk\arm-ttk\Test-AzTemplate.ps1:273 char:33
+ …                     . $myModule $TheTest @testInput 2>&1 3>&1 | # Run …
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : ApiVersion.OutOfDate,apiVersions-Should-Be-Recent.test.ps1
##[error]PowerShell exited with code '1'.`
```

My end state is that I moved the "Run ARM Test Toolkit" script to a separate file. And run powershell.exe from within the PowerShell@2 task. I do not know why this works, but it does, and it correctly fails the pipeline or errors:

```
- task: PowerShell@2
      displayName: ARM Best practices analyzer
      inputs:
        targetType: inline
        failOnStderr: true
        pwsh: true
        script: |
          Set-Location "$(Build.BinariesDirectory)/arm-ttk/arm-ttk"
          powershell.exe -noprofile -nologo -File $(Pipeline.Workspace)\s\ci-scripts\Run-TestTemplate.ps1 -TemplatePath $(Pipeline.Workspace)\s\IaC\main.json
```

What am I missing? Do you have an example?
